[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.anyhow]
version = "1.0"

[dependencies.bcrypt]
version = "0.12"

[dependencies.dotenv_codegen]
version = "0.15.0"

[dependencies.jsonwebtoken]
version = "8"

[dependencies.mongodb]
version = "2.2.2"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]

[dependencies.rocket_cors]
# version = "0.6.0-alpha1"
git = "https://github.com/lawliet89/rocket_cors"
branch = "master"

[dependencies.serde]
version = "1.0.136"
features = ["derive"]
